config/routes.rb
Rails.application.routes.draw do
 
  controller :reservation do
    get 'create' => :create
    get 'delete' => :delete
    get 'show' => :show
    get 'index' => :index  
  end

  get 'reservations/create', to: 'reservations#create'
  get 'reservations/delete', to: 'reservations#destroy'
get 'reservations', to: 'reservations#index'
  get 'book/new', to: 'books#new'
  get 'edit' , to: 'books#edit'
  get 'admin' => 'admin#index'
  get 'register' => 'users#new'
  get 'categories/new', to: 'categories#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end


  resources :users
  resources :categories
  resources :books
  resources :reservations
  root 'books#index'


  namespace :api do
    
      #method
      get 'books' => 'books#index'
      get 'book' => 'books#show'
      
      get 'categories' => 'categories#index'
      get 'category' => 'categories#show'

      post 'login' => 'userauth#login'
      post 'register' => 'registeration#register'

      get 'user' => 'users#index'
      post 'reservation' => 'reservation#show_reserved'
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
    belongs_to :reservation, class_name: "reservation", foreign_key: "reservation_id", optional: true
    has_one_attached :header_image


    def self.search(search)
        if search.blank?
        all
        else
            where('name LIKE ?', "%#{search}%")
        end
        
    end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  
  def index
    array = Array.new
    @books = Book.all
    @categories = Category.all
    @books.each do |book|
      array << {:id => book.id,
        :name => book.name,
        :price => book.price,
        :published_year => book.publish_year,
        :is_reserved => book.is_reserved,
        :categories => Category.where(id: book.category_id)					
      }
    end
    render json: array
  end
  def show
    @books = Book.all
    @categories = Category.all
    @authors = Author.all
    @book = Book.find(params[:id])
    book_array = Array.new
    book_array << {:id => @book.id,
      :name => @book.name,
      :price =>@book.price,
      :published_year => @book.publish_year,
      :is_reserved => @book.is_reserved,
      :categories => Category.where(id: @book.category_id)
    }
    render json: book_array.first
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authorize, only: [:show, :edit, :index]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
      @books = Book.search(params[:search])
      @categories = Category.all
      @reservations = Reservation.all
  
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(@book.id)
    @category = Category.find(@book.category_id)
  end

  # GET /books/new
  def new
    @book = Book.new
    @categories = Category.all
  end

  # GET /books/1/edit
  def edit
    @categories = Category
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_url, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      @book.category_id = params[:category_id]
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
      @category = @book.category
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :publish_year, :price, :added_date, :category_id, :header_image, :search)
    end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class = " container">
<div class ="row">
<div class ="col-xs-6 ">
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.label :categories %>
    <%= form.collection_select :category_id, Category.all, :id, :name, class: 'form-control' %>
  </div>

    <div class="field form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image , class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name , class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control'  %>
  </div>

  <div class="field form-group">

    <%= form.label :publish_year %>
    <%= form.text_field :publish_year, class: 'form-control'  %>
  </div>

  <div class="field form-group">

  
    <%= form.label :price %>
    <%= form.number_field :price , class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :added_date %>
    <%= form.date_select :added_date , class: 'form-control' %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div></div></div>

app/views/books/edit.html.erb
<%= render 'form', book: @book %>

app/views/books/index.html.erb
  <div class="alert alert-success" role="alert">
  <%= notice %>
</div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-6">
      <%= form_tag books_path, :method=> "get" , class:'form-inline' do%> 

        <div class="form-group mx-sm-3 mb-2">
      <%= text_field_tag :search , params[:search] , class:'form-control',placeholder:'Enter Book Name'%>
      </div>
       <%= submit_tag "Search" , :name  => nil , class:'btn btn-outline-secondary mb-2'%>
      <% end%>
  </div>

</div>
  </div>

  <div class="container">
    <div class="row-fluid">
    <div class="card-deck">
         <% @books.each do |book| %>
          <div class="col-sm-3 ">
          <div class="view overlay">
            <div class="card text-center" style="width:15rem;  margin:1rem;"> 
            <%= image_tag book.header_image.variant(resize: "300x300!"), class:'card-img'%>

    <center>
      <div class="card-body">
           <h5 class="card-title"><%= book.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted">Published in <%= book.publish_year %></h6>
      <p class="card-text">Category - <%= book.category.name %>
      </p>
      <p class="card-text">Author - <%= book.author %>
      </p>
      <p class="card-text">Price - <%= book.price%>
      </p>
      <% if session[:user_id] %>
          <% if session[:is_admin] %>
              <% if book.is_reserved %>
             <%= link_to 'Cancel Reservation', reservations_delete_path(book_id: book.id, user_id: @user_id), class:"btn btn-outline-dark btn-block" %>
              <%else%>
             <%= link_to 'Reserve Book', reservations_create_path(book_id: book.id, user_id: @user_id) , class:"btn btn-outline-dark btn-block"%></button>
              <% end %>
              
            
            <%else%>
               <%@user_id = session[:user_id]%>
             <% if book.is_reserved %>
        
               <% if Reservation.exists?(book_id: book.id, user_id: @user_id) %>
            <%= link_to 'Cancel Reservation', reservations_delete_path(book_id: book.id, user_id: @user_id), class:"btn btn-outline-dark btn-block"  %>
               <%else%>
              Book Reserved 
              <%end%>
           <%else%>
           <%= link_to 'Reserve Book', reservations_create_path(book_id: book.id, user_id: @user_id), class:"btn btn-outline-dark btn-block"  %>
              <% end %>
        
           <% end %>
      <% end %>
      </div>
  </div>
  </div>
  <center>
          </div>

         <% end%>
        </div>
    </div>
  </div>
  
  
  

app/views/books/new.html.erb
<div class="container">
<h1>Add New Book</h1>
</div>
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<center>
  <div class="card" style="width: 20rem;">
   <%= image_tag @book.header_image.variant(resize: "300x300")%>
 <div class="card-body">
      <h5 class="card-title"><%= @book.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Published in <%= @book.publish_year %></h6>
      <p class="card-text">Category - <%= @category.name %>
      </p>
      <p class="card-text">Author - <%= @book.author %>
      </p>
      <p class="card-text">Price - <%= @book.price%>
      </p>
      <% if session[:user_id] %>
      <% if session[:is_admin] %>
     <button type="button" class="btn btn-dark btn-lg btn-block"> <%= link_to 'Edit', edit_book_path(@book) %></button>
      <% end %>
      <% end %>

    </div>
  </div>
</center>