config/routes.rb
Rails.application.routes.draw do
 
  controller :reservation do
    get 'create' => :create
    get 'delete' => :delete
    get 'show' => :show
    get 'index' => :index  
  end

  get 'reservations/create', to: 'reservations#create'
  get 'reservations/delete', to: 'reservations#destroy'
get 'reservations', to: 'reservations#index'
  get 'book/new', to: 'books#new'
  get 'edit' , to: 'books#edit'
  get 'admin' => 'admin#index'
  get 'register' => 'users#new'
  get 'categories/new', to: 'categories#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end


  resources :users
  resources :categories
  resources :books
  resources :reservations
  root 'books#index'


  namespace :api do
    
      #method
      get 'books' => 'books#index'
      get 'book' => 'books#show'
      
      get 'categories' => 'categories#index'
      get 'category' => 'categories#show'

      post 'login' => 'userauth#login'
      post 'register' => 'registeration#register'

      get 'user' => 'users#index'
      post 'reservation' => 'reservation#show_reserved'
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    has_many :books
end

app/controllers/api/reservation_controller.rb
class Api::ReservationController < ApplicationController
    skip_before_action :verify_authenticity_token

    
  def show_reserved
    user_id = params[:user_id]
    book_id = params[:book_id]
    book = Book.find(book_id)
    if book.is_reserved
      
      reservation = Reservation.find_by(book_id: book.id)
      if reservation.user_id.to_s == user_id
        book.update(is_reserved: false)
        if reservation.delete
          render json: {
            message: "Reservation Cancelled.",
            book: book,
            reservation: reservation
          }                        
        else
          render json: {
            message: "Error Occured while cancelling reservation.",
            }, status: 401
          end
        else
          render json: {
            message: "Book is reserved",
            reservation_id: reservation.user_id,
            book_id: book_id,
            user_id: user_id,
            book: book
            }, status: 401
          end
        else
          book.update(is_reserved: true)
          reservation = Reservation.new(user_id: user_id, book_id: book.id)
          if reservation.save
            render json: {
              book_id: book_id,
              user_id: user_id,
              message: "You have been reserved Book",
              book: book,
              reservation: reservation
            }
          else 
            render json: {
              message: "Error Occured  while Reserving Book",
              book_id: book_id,
              user_id: user_id,
              book: book
              }, status: 401
            end
          
            
          end
          
        end
      
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authorize, only: [:show, :index]
  #before_action :set_reservation, only: [:show, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    
  end

  # GET /reservations/new

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    book = Book.find(reservation_params["book_id"])
    book.update(is_reserved: true) 
    @user_id = session[:user_id]
    @reservation = Reservation.new(user_id: @user_id, book_id: book.id)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to books_url, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    book = Book.find(reservation_params["book_id"])
    book.update(is_reserved: false)
    @user_id = session[:user_id]
    @reservation = Reservation.find_by(book_id: book.id)

  
    respond_to do |format|
      if @reservation.delete
        format.html { redirect_to books_url, notice: 'Reservation was successfully destroyed.' }
        format.json { head :no_content }
      else

      end
        

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
       params.permit(:book_id)
    end
end

app/helpers/api/reservation_helper.rb
module Api::ReservationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.book_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>