config/routes.rb
Rails.application.routes.draw do
 
  controller :reservation do
    get 'create' => :create
    get 'delete' => :delete
    get 'show' => :show
    get 'index' => :index  
  end

  get 'reservations/create', to: 'reservations#create'
  get 'reservations/delete', to: 'reservations#destroy'
get 'reservations', to: 'reservations#index'
  get 'book/new', to: 'books#new'
  get 'edit' , to: 'books#edit'
  get 'admin' => 'admin#index'
  get 'register' => 'users#new'
  get 'categories/new', to: 'categories#new'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end


  resources :users
  resources :categories
  resources :books
  resources :reservations
  root 'books#index'


  namespace :api do
    
      #method
      get 'books' => 'books#index'
      get 'book' => 'books#show'
      
      get 'categories' => 'categories#index'
      get 'category' => 'categories#show'

      post 'login' => 'userauth#login'
      post 'register' => 'registeration#register'

      get 'user' => 'users#index'
      post 'reservation' => 'reservation#show_reserved'
    
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController
    
    def index
        array = Array.new
        @categories = Category.all
        render json: @categories 
    end
    
    def show
        
        @category = Category.find(params[:id])
        @books = Book.where(category_id: @category.id)
        booklist = Array.new
        @books.each do |book|
            booklist << {:id => book.id,
                :name => book.name,
                :published_year => book.publish_year,
                :is_reserved => book.is_reserved
            }
        end
        render json: {
            category: @category,
            books: booklist
        }
        
        
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories =Category.all
    @books = Book.where(category_id: @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to book_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/api/categories_helper.rb
module Api::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class = " container">
<div class ="row">
<div class ="col-xs-6 ">
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name ,class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>No. </th>
      <th>Name</th>
      
    </tr>
  </thead>

  <tbody>
    <% @categories.each_with_index do |category ,index| %>
      <tr>
     </tr>
        <td> <%= index+1%>
        <td><%= link_to category.name, category %></td>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<table class="table">
  <thead>
    <tr>
      
      <th><%= @category.name %> 
            <% if session[:user_id] %>
      <% if session[:is_admin] %><th>Action </th>
      <%end%>
      <%end%>
    </tr>
  </thead>
  <tbody>
    
      <% @books.each do |book| %>
      <tr>
      <td>
        <%= book.name %> 
      </td>
            <% if session[:user_id] %>
      <% if session[:is_admin] %>
      <td>
      <%= link_to 'Edit', edit_category_path(@category) %></th>
     
      </td>
      <%end%>
      <%end%>
      </tr>
      <% end %>

  </tbody>
</table>